namespace SwiftPOS1
{
    partial class Menu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.siticonePanel1 = new SiticoneNetFrameworkUI.SiticonePanel();
            this.siticoneLabel1 = new SiticoneNetFrameworkUI.SiticoneLabel();
            this.btnInventory = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnSales = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton1 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton2 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton3 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton4 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton5 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton6 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneButton7 = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnMenu = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticonePanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // siticonePanel1
            // 
            this.siticonePanel1.AcrylicTintColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.BackColor = System.Drawing.Color.Transparent;
            this.siticonePanel1.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            this.siticonePanel1.BorderDashPattern = null;
            this.siticonePanel1.BorderGradientEndColor = System.Drawing.Color.SeaGreen;
            this.siticonePanel1.BorderGradientStartColor = System.Drawing.Color.ForestGreen;
            this.siticonePanel1.BorderThickness = 2F;
            this.siticonePanel1.Controls.Add(this.siticoneButton7);
            this.siticonePanel1.Controls.Add(this.siticoneLabel1);
            this.siticonePanel1.Controls.Add(this.btnMenu);
            this.siticonePanel1.Controls.Add(this.btnInventory);
            this.siticonePanel1.Controls.Add(this.btnSales);
            this.siticonePanel1.CornerRadiusBottomLeft = 40F;
            this.siticonePanel1.CornerRadiusBottomRight = 40F;
            this.siticonePanel1.CornerRadiusTopLeft = 40F;
            this.siticonePanel1.CornerRadiusTopRight = 40F;
            this.siticonePanel1.EnableAcrylicEffect = false;
            this.siticonePanel1.EnableMicaEffect = false;
            this.siticonePanel1.EnableRippleEffect = false;
            this.siticonePanel1.FillColor = System.Drawing.Color.DarkSeaGreen;
            this.siticonePanel1.GradientColors = new System.Drawing.Color[] {
        System.Drawing.Color.White,
        System.Drawing.Color.LightGray,
        System.Drawing.Color.Gray};
            this.siticonePanel1.GradientPositions = new float[] {
        0F,
        0.5F,
        1F};
            this.siticonePanel1.Location = new System.Drawing.Point(-35, -3);
            this.siticonePanel1.Name = "siticonePanel1";
            this.siticonePanel1.PatternStyle = System.Drawing.Drawing2D.HatchStyle.LargeGrid;
            this.siticonePanel1.RippleAlpha = 50;
            this.siticonePanel1.RippleAlphaDecrement = 3;
            this.siticonePanel1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.RippleMaxSize = 600F;
            this.siticonePanel1.RippleSpeed = 15F;
            this.siticonePanel1.ShowBorder = true;
            this.siticonePanel1.Size = new System.Drawing.Size(232, 1034);
            this.siticonePanel1.TabIndex = 1;
            this.siticonePanel1.TabStop = true;
            this.siticonePanel1.TrackSystemTheme = false;
            this.siticonePanel1.UseBorderGradient = true;
            this.siticonePanel1.UseMultiGradient = false;
            this.siticonePanel1.UsePatternTexture = false;
            this.siticonePanel1.UseRadialGradient = false;
            // 
            // siticoneLabel1
            // 
            this.siticoneLabel1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneLabel1.Font = new System.Drawing.Font("Times New Roman", 26.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneLabel1.Location = new System.Drawing.Point(70, 69);
            this.siticoneLabel1.Name = "siticoneLabel1";
            this.siticoneLabel1.Size = new System.Drawing.Size(119, 48);
            this.siticoneLabel1.TabIndex = 3;
            this.siticoneLabel1.Text = "Cafero";
            // 
            // btnInventory
            // 
            this.btnInventory.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnInventory.AccessibleName = "Inventory";
            this.btnInventory.AutoSizeBasedOnText = false;
            this.btnInventory.BackColor = System.Drawing.Color.Transparent;
            this.btnInventory.BadgeBackColor = System.Drawing.Color.Black;
            this.btnInventory.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnInventory.BadgeValue = 0;
            this.btnInventory.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnInventory.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnInventory.BorderWidth = 2;
            this.btnInventory.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnInventory.ButtonImage = null;
            this.btnInventory.ButtonTextLeftPadding = 0;
            this.btnInventory.CanBeep = true;
            this.btnInventory.CanGlow = true;
            this.btnInventory.CanShake = true;
            this.btnInventory.ContextMenuStripEx = null;
            this.btnInventory.CornerRadiusBottomLeft = 19;
            this.btnInventory.CornerRadiusBottomRight = 19;
            this.btnInventory.CornerRadiusTopLeft = 19;
            this.btnInventory.CornerRadiusTopRight = 19;
            this.btnInventory.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnInventory.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnInventory.EnableLongPress = false;
            this.btnInventory.EnableRippleEffect = true;
            this.btnInventory.EnableShadow = false;
            this.btnInventory.EnableTextWrapping = false;
            this.btnInventory.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F);
            this.btnInventory.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnInventory.GlowIntensity = 100;
            this.btnInventory.GlowRadius = 20F;
            this.btnInventory.GradientBackground = false;
            this.btnInventory.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnInventory.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnInventory.HintText = null;
            this.btnInventory.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnInventory.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.HoverTextColor = System.Drawing.Color.White;
            this.btnInventory.HoverTransitionDuration = 250;
            this.btnInventory.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInventory.ImagePadding = 5;
            this.btnInventory.ImageSize = new System.Drawing.Size(16, 16);
            this.btnInventory.IsRadial = true;
            this.btnInventory.IsReadOnly = false;
            this.btnInventory.IsToggleButton = false;
            this.btnInventory.IsToggled = false;
            this.btnInventory.Location = new System.Drawing.Point(50, 249);
            this.btnInventory.LongPressDurationMS = 1000;
            this.btnInventory.Name = "btnInventory";
            this.btnInventory.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnInventory.ParticleCount = 15;
            this.btnInventory.PressAnimationScale = 0.97F;
            this.btnInventory.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnInventory.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.PressTransitionDuration = 150;
            this.btnInventory.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnInventory.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnInventory.RippleOpacity = 0.2F;
            this.btnInventory.RippleRadiusMultiplier = 0.6F;
            this.btnInventory.ShadowBlur = 6;
            this.btnInventory.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInventory.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnInventory.ShakeDuration = 500;
            this.btnInventory.ShakeIntensity = 5;
            this.btnInventory.Size = new System.Drawing.Size(154, 42);
            this.btnInventory.TabIndex = 1;
            this.btnInventory.Text = "Inventory";
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInventory.TextColor = System.Drawing.Color.White;
            this.btnInventory.TooltipText = null;
            this.btnInventory.UseAdvancedRendering = true;
            this.btnInventory.UseParticles = false;
            // 
            // btnSales
            // 
            this.btnSales.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnSales.AccessibleName = "Analytics";
            this.btnSales.AutoSizeBasedOnText = false;
            this.btnSales.BackColor = System.Drawing.Color.Transparent;
            this.btnSales.BadgeBackColor = System.Drawing.Color.Black;
            this.btnSales.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnSales.BadgeValue = 0;
            this.btnSales.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnSales.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnSales.BorderWidth = 2;
            this.btnSales.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnSales.ButtonImage = null;
            this.btnSales.ButtonTextLeftPadding = 0;
            this.btnSales.CanBeep = true;
            this.btnSales.CanGlow = true;
            this.btnSales.CanShake = true;
            this.btnSales.ContextMenuStripEx = null;
            this.btnSales.CornerRadiusBottomLeft = 19;
            this.btnSales.CornerRadiusBottomRight = 19;
            this.btnSales.CornerRadiusTopLeft = 19;
            this.btnSales.CornerRadiusTopRight = 19;
            this.btnSales.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnSales.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnSales.EnableLongPress = false;
            this.btnSales.EnableRippleEffect = true;
            this.btnSales.EnableShadow = false;
            this.btnSales.EnableTextWrapping = false;
            this.btnSales.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F);
            this.btnSales.GlowColor = System.Drawing.Color.Transparent;
            this.btnSales.GlowIntensity = 100;
            this.btnSales.GlowRadius = 20F;
            this.btnSales.GradientBackground = false;
            this.btnSales.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnSales.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnSales.HintText = null;
            this.btnSales.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnSales.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.HoverTextColor = System.Drawing.Color.White;
            this.btnSales.HoverTransitionDuration = 250;
            this.btnSales.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSales.ImagePadding = 5;
            this.btnSales.ImageSize = new System.Drawing.Size(16, 16);
            this.btnSales.IsRadial = true;
            this.btnSales.IsReadOnly = false;
            this.btnSales.IsToggleButton = false;
            this.btnSales.IsToggled = false;
            this.btnSales.Location = new System.Drawing.Point(50, 323);
            this.btnSales.LongPressDurationMS = 1000;
            this.btnSales.Name = "btnSales";
            this.btnSales.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnSales.ParticleCount = 15;
            this.btnSales.PressAnimationScale = 0.97F;
            this.btnSales.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnSales.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.PressTransitionDuration = 150;
            this.btnSales.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnSales.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnSales.RippleOpacity = 0.2F;
            this.btnSales.RippleRadiusMultiplier = 0.6F;
            this.btnSales.ShadowBlur = 6;
            this.btnSales.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnSales.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnSales.ShakeDuration = 500;
            this.btnSales.ShakeIntensity = 5;
            this.btnSales.Size = new System.Drawing.Size(154, 42);
            this.btnSales.TabIndex = 0;
            this.btnSales.Text = "Analytics";
            this.btnSales.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSales.TextColor = System.Drawing.Color.White;
            this.btnSales.TooltipText = null;
            this.btnSales.UseAdvancedRendering = true;
            this.btnSales.UseParticles = false;
            this.btnSales.Click += new System.EventHandler(this.btnSales_Click);
            // 
            // siticoneButton1
            // 
            this.siticoneButton1.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton1.AccessibleName = "COFFEE";
            this.siticoneButton1.AutoSizeBasedOnText = false;
            this.siticoneButton1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton1.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton1.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton1.BadgeValue = 0;
            this.siticoneButton1.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton1.BorderColor = System.Drawing.Color.Tan;
            this.siticoneButton1.BorderWidth = 2;
            this.siticoneButton1.ButtonBackColor = System.Drawing.Color.Tan;
            this.siticoneButton1.ButtonImage = null;
            this.siticoneButton1.ButtonTextLeftPadding = 0;
            this.siticoneButton1.CanBeep = true;
            this.siticoneButton1.CanGlow = true;
            this.siticoneButton1.CanShake = true;
            this.siticoneButton1.ContextMenuStripEx = null;
            this.siticoneButton1.CornerRadiusBottomLeft = 23;
            this.siticoneButton1.CornerRadiusBottomRight = 23;
            this.siticoneButton1.CornerRadiusTopLeft = 23;
            this.siticoneButton1.CornerRadiusTopRight = 23;
            this.siticoneButton1.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton1.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton1.EnableLongPress = false;
            this.siticoneButton1.EnableRippleEffect = true;
            this.siticoneButton1.EnableShadow = false;
            this.siticoneButton1.EnableTextWrapping = false;
            this.siticoneButton1.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton1.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton1.GlowIntensity = 100;
            this.siticoneButton1.GlowRadius = 20F;
            this.siticoneButton1.GradientBackground = false;
            this.siticoneButton1.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton1.HintText = null;
            this.siticoneButton1.HoverBackColor = System.Drawing.Color.Transparent;
            this.siticoneButton1.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.HoverTextColor = System.Drawing.Color.Black;
            this.siticoneButton1.HoverTransitionDuration = 250;
            this.siticoneButton1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton1.ImagePadding = 5;
            this.siticoneButton1.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton1.IsRadial = true;
            this.siticoneButton1.IsReadOnly = false;
            this.siticoneButton1.IsToggleButton = false;
            this.siticoneButton1.IsToggled = false;
            this.siticoneButton1.Location = new System.Drawing.Point(265, 70);
            this.siticoneButton1.LongPressDurationMS = 1000;
            this.siticoneButton1.Name = "siticoneButton1";
            this.siticoneButton1.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton1.ParticleCount = 15;
            this.siticoneButton1.PressAnimationScale = 0.97F;
            this.siticoneButton1.PressedBackColor = System.Drawing.Color.Transparent;
            this.siticoneButton1.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton1.PressTransitionDuration = 150;
            this.siticoneButton1.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton1.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton1.ShadowBlur = 5;
            this.siticoneButton1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton1.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton1.ShakeDuration = 500;
            this.siticoneButton1.ShakeIntensity = 5;
            this.siticoneButton1.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton1.TabIndex = 2;
            this.siticoneButton1.Text = "COFFEE";
            this.siticoneButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton1.TextColor = System.Drawing.Color.Black;
            this.siticoneButton1.TooltipText = null;
            this.siticoneButton1.UseAdvancedRendering = true;
            this.siticoneButton1.UseParticles = false;
            // 
            // siticoneButton2
            // 
            this.siticoneButton2.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton2.AccessibleName = "MILKTEA";
            this.siticoneButton2.AutoSizeBasedOnText = false;
            this.siticoneButton2.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton2.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton2.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton2.BadgeValue = 0;
            this.siticoneButton2.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticoneButton2.BorderWidth = 2;
            this.siticoneButton2.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.siticoneButton2.ButtonImage = null;
            this.siticoneButton2.ButtonTextLeftPadding = 0;
            this.siticoneButton2.CanBeep = true;
            this.siticoneButton2.CanGlow = true;
            this.siticoneButton2.CanShake = true;
            this.siticoneButton2.ContextMenuStripEx = null;
            this.siticoneButton2.CornerRadiusBottomLeft = 23;
            this.siticoneButton2.CornerRadiusBottomRight = 23;
            this.siticoneButton2.CornerRadiusTopLeft = 23;
            this.siticoneButton2.CornerRadiusTopRight = 23;
            this.siticoneButton2.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton2.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton2.EnableLongPress = false;
            this.siticoneButton2.EnableRippleEffect = true;
            this.siticoneButton2.EnableShadow = false;
            this.siticoneButton2.EnableTextWrapping = false;
            this.siticoneButton2.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton2.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton2.GlowIntensity = 100;
            this.siticoneButton2.GlowRadius = 20F;
            this.siticoneButton2.GradientBackground = false;
            this.siticoneButton2.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton2.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton2.HintText = null;
            this.siticoneButton2.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.siticoneButton2.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton2.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton2.HoverTransitionDuration = 250;
            this.siticoneButton2.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton2.ImagePadding = 5;
            this.siticoneButton2.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton2.IsRadial = true;
            this.siticoneButton2.IsReadOnly = false;
            this.siticoneButton2.IsToggleButton = false;
            this.siticoneButton2.IsToggled = false;
            this.siticoneButton2.Location = new System.Drawing.Point(500, 70);
            this.siticoneButton2.LongPressDurationMS = 1000;
            this.siticoneButton2.Name = "siticoneButton2";
            this.siticoneButton2.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton2.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton2.ParticleCount = 15;
            this.siticoneButton2.PressAnimationScale = 0.97F;
            this.siticoneButton2.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.siticoneButton2.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton2.PressTransitionDuration = 150;
            this.siticoneButton2.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton2.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton2.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton2.ShadowBlur = 5;
            this.siticoneButton2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton2.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton2.ShakeDuration = 500;
            this.siticoneButton2.ShakeIntensity = 5;
            this.siticoneButton2.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton2.TabIndex = 3;
            this.siticoneButton2.Text = "MILKTEA";
            this.siticoneButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton2.TextColor = System.Drawing.Color.White;
            this.siticoneButton2.TooltipText = null;
            this.siticoneButton2.UseAdvancedRendering = true;
            this.siticoneButton2.UseParticles = false;
            // 
            // siticoneButton3
            // 
            this.siticoneButton3.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton3.AccessibleName = "RICE MEAL";
            this.siticoneButton3.AutoSizeBasedOnText = false;
            this.siticoneButton3.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton3.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton3.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton3.BadgeValue = 0;
            this.siticoneButton3.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticoneButton3.BorderWidth = 2;
            this.siticoneButton3.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.siticoneButton3.ButtonImage = null;
            this.siticoneButton3.ButtonTextLeftPadding = 0;
            this.siticoneButton3.CanBeep = true;
            this.siticoneButton3.CanGlow = true;
            this.siticoneButton3.CanShake = true;
            this.siticoneButton3.ContextMenuStripEx = null;
            this.siticoneButton3.CornerRadiusBottomLeft = 23;
            this.siticoneButton3.CornerRadiusBottomRight = 23;
            this.siticoneButton3.CornerRadiusTopLeft = 23;
            this.siticoneButton3.CornerRadiusTopRight = 23;
            this.siticoneButton3.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton3.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton3.EnableLongPress = false;
            this.siticoneButton3.EnableRippleEffect = true;
            this.siticoneButton3.EnableShadow = false;
            this.siticoneButton3.EnableTextWrapping = false;
            this.siticoneButton3.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton3.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton3.GlowIntensity = 100;
            this.siticoneButton3.GlowRadius = 20F;
            this.siticoneButton3.GradientBackground = false;
            this.siticoneButton3.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton3.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton3.HintText = null;
            this.siticoneButton3.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.siticoneButton3.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton3.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton3.HoverTransitionDuration = 250;
            this.siticoneButton3.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton3.ImagePadding = 5;
            this.siticoneButton3.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton3.IsRadial = true;
            this.siticoneButton3.IsReadOnly = false;
            this.siticoneButton3.IsToggleButton = false;
            this.siticoneButton3.IsToggled = false;
            this.siticoneButton3.Location = new System.Drawing.Point(972, 70);
            this.siticoneButton3.LongPressDurationMS = 1000;
            this.siticoneButton3.Name = "siticoneButton3";
            this.siticoneButton3.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton3.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton3.ParticleCount = 15;
            this.siticoneButton3.PressAnimationScale = 0.97F;
            this.siticoneButton3.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.siticoneButton3.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton3.PressTransitionDuration = 150;
            this.siticoneButton3.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton3.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton3.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton3.ShadowBlur = 5;
            this.siticoneButton3.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton3.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton3.ShakeDuration = 500;
            this.siticoneButton3.ShakeIntensity = 5;
            this.siticoneButton3.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton3.TabIndex = 4;
            this.siticoneButton3.Text = "RICE MEAL";
            this.siticoneButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton3.TextColor = System.Drawing.Color.White;
            this.siticoneButton3.TooltipText = null;
            this.siticoneButton3.UseAdvancedRendering = true;
            this.siticoneButton3.UseParticles = false;
            // 
            // siticoneButton4
            // 
            this.siticoneButton4.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton4.AccessibleName = "FRUIT TEA";
            this.siticoneButton4.AutoSizeBasedOnText = false;
            this.siticoneButton4.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton4.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton4.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton4.BadgeValue = 0;
            this.siticoneButton4.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticoneButton4.BorderWidth = 2;
            this.siticoneButton4.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.siticoneButton4.ButtonImage = null;
            this.siticoneButton4.ButtonTextLeftPadding = 0;
            this.siticoneButton4.CanBeep = true;
            this.siticoneButton4.CanGlow = true;
            this.siticoneButton4.CanShake = true;
            this.siticoneButton4.ContextMenuStripEx = null;
            this.siticoneButton4.CornerRadiusBottomLeft = 23;
            this.siticoneButton4.CornerRadiusBottomRight = 23;
            this.siticoneButton4.CornerRadiusTopLeft = 23;
            this.siticoneButton4.CornerRadiusTopRight = 23;
            this.siticoneButton4.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton4.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton4.EnableLongPress = false;
            this.siticoneButton4.EnableRippleEffect = true;
            this.siticoneButton4.EnableShadow = false;
            this.siticoneButton4.EnableTextWrapping = false;
            this.siticoneButton4.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton4.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton4.GlowIntensity = 100;
            this.siticoneButton4.GlowRadius = 20F;
            this.siticoneButton4.GradientBackground = false;
            this.siticoneButton4.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton4.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton4.HintText = null;
            this.siticoneButton4.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.siticoneButton4.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton4.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton4.HoverTransitionDuration = 250;
            this.siticoneButton4.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton4.ImagePadding = 5;
            this.siticoneButton4.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton4.IsRadial = true;
            this.siticoneButton4.IsReadOnly = false;
            this.siticoneButton4.IsToggleButton = false;
            this.siticoneButton4.IsToggled = false;
            this.siticoneButton4.Location = new System.Drawing.Point(726, 70);
            this.siticoneButton4.LongPressDurationMS = 1000;
            this.siticoneButton4.Name = "siticoneButton4";
            this.siticoneButton4.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton4.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton4.ParticleCount = 15;
            this.siticoneButton4.PressAnimationScale = 0.97F;
            this.siticoneButton4.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.siticoneButton4.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton4.PressTransitionDuration = 150;
            this.siticoneButton4.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton4.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton4.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton4.ShadowBlur = 5;
            this.siticoneButton4.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton4.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton4.ShakeDuration = 500;
            this.siticoneButton4.ShakeIntensity = 5;
            this.siticoneButton4.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton4.TabIndex = 5;
            this.siticoneButton4.Text = "FRUIT TEA";
            this.siticoneButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton4.TextColor = System.Drawing.Color.White;
            this.siticoneButton4.TooltipText = null;
            this.siticoneButton4.UseAdvancedRendering = true;
            this.siticoneButton4.UseParticles = false;
            // 
            // siticoneButton5
            // 
            this.siticoneButton5.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton5.AccessibleName = "PASTRY";
            this.siticoneButton5.AutoSizeBasedOnText = false;
            this.siticoneButton5.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton5.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton5.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton5.BadgeValue = 0;
            this.siticoneButton5.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticoneButton5.BorderWidth = 2;
            this.siticoneButton5.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.siticoneButton5.ButtonImage = null;
            this.siticoneButton5.ButtonTextLeftPadding = 0;
            this.siticoneButton5.CanBeep = true;
            this.siticoneButton5.CanGlow = true;
            this.siticoneButton5.CanShake = true;
            this.siticoneButton5.ContextMenuStripEx = null;
            this.siticoneButton5.CornerRadiusBottomLeft = 23;
            this.siticoneButton5.CornerRadiusBottomRight = 23;
            this.siticoneButton5.CornerRadiusTopLeft = 23;
            this.siticoneButton5.CornerRadiusTopRight = 23;
            this.siticoneButton5.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton5.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton5.EnableLongPress = false;
            this.siticoneButton5.EnableRippleEffect = true;
            this.siticoneButton5.EnableShadow = false;
            this.siticoneButton5.EnableTextWrapping = false;
            this.siticoneButton5.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton5.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton5.GlowIntensity = 100;
            this.siticoneButton5.GlowRadius = 20F;
            this.siticoneButton5.GradientBackground = false;
            this.siticoneButton5.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton5.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton5.HintText = null;
            this.siticoneButton5.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.siticoneButton5.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton5.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton5.HoverTransitionDuration = 250;
            this.siticoneButton5.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton5.ImagePadding = 5;
            this.siticoneButton5.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton5.IsRadial = true;
            this.siticoneButton5.IsReadOnly = false;
            this.siticoneButton5.IsToggleButton = false;
            this.siticoneButton5.IsToggled = false;
            this.siticoneButton5.Location = new System.Drawing.Point(1218, 70);
            this.siticoneButton5.LongPressDurationMS = 1000;
            this.siticoneButton5.Name = "siticoneButton5";
            this.siticoneButton5.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton5.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton5.ParticleCount = 15;
            this.siticoneButton5.PressAnimationScale = 0.97F;
            this.siticoneButton5.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.siticoneButton5.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton5.PressTransitionDuration = 150;
            this.siticoneButton5.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton5.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton5.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton5.ShadowBlur = 5;
            this.siticoneButton5.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton5.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton5.ShakeDuration = 500;
            this.siticoneButton5.ShakeIntensity = 5;
            this.siticoneButton5.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton5.TabIndex = 6;
            this.siticoneButton5.Text = "PASTRY";
            this.siticoneButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton5.TextColor = System.Drawing.Color.White;
            this.siticoneButton5.TooltipText = null;
            this.siticoneButton5.UseAdvancedRendering = true;
            this.siticoneButton5.UseParticles = false;
            // 
            // siticoneButton6
            // 
            this.siticoneButton6.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton6.AccessibleName = "SNACKS AND PASTA";
            this.siticoneButton6.AutoSizeBasedOnText = false;
            this.siticoneButton6.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton6.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton6.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton6.BadgeValue = 0;
            this.siticoneButton6.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.siticoneButton6.BorderWidth = 2;
            this.siticoneButton6.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.siticoneButton6.ButtonImage = null;
            this.siticoneButton6.ButtonTextLeftPadding = 0;
            this.siticoneButton6.CanBeep = true;
            this.siticoneButton6.CanGlow = true;
            this.siticoneButton6.CanShake = true;
            this.siticoneButton6.ContextMenuStripEx = null;
            this.siticoneButton6.CornerRadiusBottomLeft = 23;
            this.siticoneButton6.CornerRadiusBottomRight = 23;
            this.siticoneButton6.CornerRadiusTopLeft = 23;
            this.siticoneButton6.CornerRadiusTopRight = 23;
            this.siticoneButton6.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton6.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton6.EnableLongPress = false;
            this.siticoneButton6.EnableRippleEffect = true;
            this.siticoneButton6.EnableShadow = false;
            this.siticoneButton6.EnableTextWrapping = false;
            this.siticoneButton6.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneButton6.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton6.GlowIntensity = 100;
            this.siticoneButton6.GlowRadius = 20F;
            this.siticoneButton6.GradientBackground = false;
            this.siticoneButton6.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton6.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton6.HintText = null;
            this.siticoneButton6.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.siticoneButton6.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton6.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton6.HoverTransitionDuration = 250;
            this.siticoneButton6.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton6.ImagePadding = 5;
            this.siticoneButton6.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton6.IsRadial = true;
            this.siticoneButton6.IsReadOnly = false;
            this.siticoneButton6.IsToggleButton = false;
            this.siticoneButton6.IsToggled = false;
            this.siticoneButton6.Location = new System.Drawing.Point(1484, 70);
            this.siticoneButton6.LongPressDurationMS = 1000;
            this.siticoneButton6.Name = "siticoneButton6";
            this.siticoneButton6.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton6.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton6.ParticleCount = 15;
            this.siticoneButton6.PressAnimationScale = 0.97F;
            this.siticoneButton6.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.siticoneButton6.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton6.PressTransitionDuration = 150;
            this.siticoneButton6.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton6.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton6.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton6.ShadowBlur = 5;
            this.siticoneButton6.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton6.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton6.ShakeDuration = 500;
            this.siticoneButton6.ShakeIntensity = 5;
            this.siticoneButton6.Size = new System.Drawing.Size(190, 50);
            this.siticoneButton6.TabIndex = 7;
            this.siticoneButton6.Text = "SNACKS AND PASTA";
            this.siticoneButton6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton6.TextColor = System.Drawing.Color.White;
            this.siticoneButton6.TooltipText = null;
            this.siticoneButton6.UseAdvancedRendering = true;
            this.siticoneButton6.UseParticles = false;
            // 
            // siticoneButton7
            // 
            this.siticoneButton7.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.siticoneButton7.AccessibleName = "Payments";
            this.siticoneButton7.AutoSizeBasedOnText = false;
            this.siticoneButton7.BackColor = System.Drawing.Color.Transparent;
            this.siticoneButton7.BadgeBackColor = System.Drawing.Color.Black;
            this.siticoneButton7.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.siticoneButton7.BadgeValue = 0;
            this.siticoneButton7.BadgeValueForeColor = System.Drawing.Color.White;
            this.siticoneButton7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.siticoneButton7.BorderWidth = 2;
            this.siticoneButton7.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.siticoneButton7.ButtonImage = null;
            this.siticoneButton7.ButtonTextLeftPadding = 0;
            this.siticoneButton7.CanBeep = true;
            this.siticoneButton7.CanGlow = true;
            this.siticoneButton7.CanShake = true;
            this.siticoneButton7.ContextMenuStripEx = null;
            this.siticoneButton7.CornerRadiusBottomLeft = 19;
            this.siticoneButton7.CornerRadiusBottomRight = 19;
            this.siticoneButton7.CornerRadiusTopLeft = 19;
            this.siticoneButton7.CornerRadiusTopRight = 19;
            this.siticoneButton7.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.siticoneButton7.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.siticoneButton7.EnableLongPress = false;
            this.siticoneButton7.EnableRippleEffect = true;
            this.siticoneButton7.EnableShadow = false;
            this.siticoneButton7.EnableTextWrapping = false;
            this.siticoneButton7.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F);
            this.siticoneButton7.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.siticoneButton7.GlowIntensity = 100;
            this.siticoneButton7.GlowRadius = 20F;
            this.siticoneButton7.GradientBackground = false;
            this.siticoneButton7.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.siticoneButton7.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.siticoneButton7.HintText = null;
            this.siticoneButton7.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.siticoneButton7.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton7.HoverTextColor = System.Drawing.Color.White;
            this.siticoneButton7.HoverTransitionDuration = 250;
            this.siticoneButton7.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.siticoneButton7.ImagePadding = 5;
            this.siticoneButton7.ImageSize = new System.Drawing.Size(16, 16);
            this.siticoneButton7.IsRadial = true;
            this.siticoneButton7.IsReadOnly = false;
            this.siticoneButton7.IsToggleButton = false;
            this.siticoneButton7.IsToggled = false;
            this.siticoneButton7.Location = new System.Drawing.Point(50, 403);
            this.siticoneButton7.LongPressDurationMS = 1000;
            this.siticoneButton7.Name = "siticoneButton7";
            this.siticoneButton7.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton7.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.siticoneButton7.ParticleCount = 15;
            this.siticoneButton7.PressAnimationScale = 0.97F;
            this.siticoneButton7.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.siticoneButton7.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.siticoneButton7.PressTransitionDuration = 150;
            this.siticoneButton7.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.siticoneButton7.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticoneButton7.RippleOpacity = 0.2F;
            this.siticoneButton7.RippleRadiusMultiplier = 0.6F;
            this.siticoneButton7.ShadowBlur = 6;
            this.siticoneButton7.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.siticoneButton7.ShadowOffset = new System.Drawing.Point(0, 2);
            this.siticoneButton7.ShakeDuration = 500;
            this.siticoneButton7.ShakeIntensity = 5;
            this.siticoneButton7.Size = new System.Drawing.Size(154, 42);
            this.siticoneButton7.TabIndex = 4;
            this.siticoneButton7.Text = "Payments";
            this.siticoneButton7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.siticoneButton7.TextColor = System.Drawing.Color.White;
            this.siticoneButton7.TooltipText = null;
            this.siticoneButton7.UseAdvancedRendering = true;
            this.siticoneButton7.UseParticles = false;
            // 
            // btnMenu
            // 
            this.btnMenu.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnMenu.AccessibleName = "Menu";
            this.btnMenu.AutoSizeBasedOnText = false;
            this.btnMenu.BackColor = System.Drawing.Color.Transparent;
            this.btnMenu.BadgeBackColor = System.Drawing.Color.Black;
            this.btnMenu.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnMenu.BadgeValue = 0;
            this.btnMenu.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnMenu.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnMenu.BorderWidth = 2;
            this.btnMenu.ButtonBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.btnMenu.ButtonImage = null;
            this.btnMenu.ButtonTextLeftPadding = 0;
            this.btnMenu.CanBeep = true;
            this.btnMenu.CanGlow = true;
            this.btnMenu.CanShake = true;
            this.btnMenu.ContextMenuStripEx = null;
            this.btnMenu.CornerRadiusBottomLeft = 19;
            this.btnMenu.CornerRadiusBottomRight = 19;
            this.btnMenu.CornerRadiusTopLeft = 19;
            this.btnMenu.CornerRadiusTopRight = 19;
            this.btnMenu.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnMenu.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnMenu.EnableLongPress = false;
            this.btnMenu.EnableRippleEffect = true;
            this.btnMenu.EnableShadow = false;
            this.btnMenu.EnableTextWrapping = false;
            this.btnMenu.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F);
            this.btnMenu.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnMenu.GlowIntensity = 100;
            this.btnMenu.GlowRadius = 20F;
            this.btnMenu.GradientBackground = false;
            this.btnMenu.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnMenu.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnMenu.HintText = null;
            this.btnMenu.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnMenu.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.HoverTextColor = System.Drawing.Color.White;
            this.btnMenu.HoverTransitionDuration = 250;
            this.btnMenu.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMenu.ImagePadding = 5;
            this.btnMenu.ImageSize = new System.Drawing.Size(16, 16);
            this.btnMenu.IsRadial = true;
            this.btnMenu.IsReadOnly = false;
            this.btnMenu.IsToggleButton = false;
            this.btnMenu.IsToggled = false;
            this.btnMenu.Location = new System.Drawing.Point(50, 169);
            this.btnMenu.LongPressDurationMS = 1000;
            this.btnMenu.Name = "btnMenu";
            this.btnMenu.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnMenu.ParticleCount = 15;
            this.btnMenu.PressAnimationScale = 0.97F;
            this.btnMenu.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnMenu.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.PressTransitionDuration = 150;
            this.btnMenu.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnMenu.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnMenu.RippleOpacity = 0.2F;
            this.btnMenu.RippleRadiusMultiplier = 0.6F;
            this.btnMenu.ShadowBlur = 6;
            this.btnMenu.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnMenu.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnMenu.ShakeDuration = 500;
            this.btnMenu.ShakeIntensity = 5;
            this.btnMenu.Size = new System.Drawing.Size(154, 42);
            this.btnMenu.TabIndex = 2;
            this.btnMenu.Text = "Menu";
            this.btnMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMenu.TextColor = System.Drawing.Color.White;
            this.btnMenu.TooltipText = null;
            this.btnMenu.UseAdvancedRendering = true;
            this.btnMenu.UseParticles = false;
            // 
            // Menu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1924, 1061);
            this.Controls.Add(this.siticoneButton6);
            this.Controls.Add(this.siticoneButton5);
            this.Controls.Add(this.siticoneButton4);
            this.Controls.Add(this.siticoneButton3);
            this.Controls.Add(this.siticoneButton2);
            this.Controls.Add(this.siticoneButton1);
            this.Controls.Add(this.siticonePanel1);
            this.Name = "Menu";
            this.Text = "Menu";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.siticonePanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private SiticoneNetFrameworkUI.SiticonePanel siticonePanel1;
        private SiticoneNetFrameworkUI.SiticoneLabel siticoneLabel1;
        private SiticoneNetFrameworkUI.SiticoneButton btnInventory;
        private SiticoneNetFrameworkUI.SiticoneButton btnSales;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton1;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton2;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton3;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton4;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton5;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton6;
        private SiticoneNetFrameworkUI.SiticoneButton siticoneButton7;
        private SiticoneNetFrameworkUI.SiticoneButton btnMenu;
    }
}