namespace SwiftPOS1
{
    partial class Menu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Menu));
            this.siticonePanel1 = new SiticoneNetFrameworkUI.SiticonePanel();
            this.btnCart = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnLogout = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticoneLabel1 = new SiticoneNetFrameworkUI.SiticoneLabel();
            this.btnMenu = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnInventory = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnSales = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnCoffee = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnMilktea = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnFruitTea = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnRiceMeal = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnPastry = new SiticoneNetFrameworkUI.SiticoneButton();
            this.btnSnacksPasta = new SiticoneNetFrameworkUI.SiticoneButton();
            this.siticonePanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // siticonePanel1
            // 
            this.siticonePanel1.AcrylicTintColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.BackColor = System.Drawing.Color.Transparent;
            this.siticonePanel1.BorderAlignment = System.Drawing.Drawing2D.PenAlignment.Center;
            this.siticonePanel1.BorderDashPattern = null;
            this.siticonePanel1.BorderGradientEndColor = System.Drawing.Color.SeaGreen;
            this.siticonePanel1.BorderGradientStartColor = System.Drawing.Color.ForestGreen;
            this.siticonePanel1.BorderThickness = 2F;
            this.siticonePanel1.Controls.Add(this.btnCart);
            this.siticonePanel1.Controls.Add(this.btnLogout);
            this.siticonePanel1.Controls.Add(this.siticoneLabel1);
            this.siticonePanel1.Controls.Add(this.btnMenu);
            this.siticonePanel1.Controls.Add(this.btnInventory);
            this.siticonePanel1.Controls.Add(this.btnSales);
            this.siticonePanel1.CornerRadiusBottomLeft = 40F;
            this.siticonePanel1.CornerRadiusBottomRight = 40F;
            this.siticonePanel1.CornerRadiusTopLeft = 40F;
            this.siticonePanel1.CornerRadiusTopRight = 40F;
            this.siticonePanel1.EnableAcrylicEffect = false;
            this.siticonePanel1.EnableMicaEffect = false;
            this.siticonePanel1.EnableRippleEffect = false;
            this.siticonePanel1.FillColor = System.Drawing.Color.DarkSeaGreen;
            this.siticonePanel1.GradientColors = new System.Drawing.Color[] {
        System.Drawing.Color.White,
        System.Drawing.Color.LightGray,
        System.Drawing.Color.Gray};
            this.siticonePanel1.GradientPositions = new float[] {
        0F,
        0.5F,
        1F};
            this.siticonePanel1.Location = new System.Drawing.Point(-35, -7);
            this.siticonePanel1.Name = "siticonePanel1";
            this.siticonePanel1.PatternStyle = System.Drawing.Drawing2D.HatchStyle.LargeGrid;
            this.siticonePanel1.RippleAlpha = 50;
            this.siticonePanel1.RippleAlphaDecrement = 3;
            this.siticonePanel1.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.siticonePanel1.RippleMaxSize = 600F;
            this.siticonePanel1.RippleSpeed = 15F;
            this.siticonePanel1.ShowBorder = true;
            this.siticonePanel1.Size = new System.Drawing.Size(232, 1038);
            this.siticonePanel1.TabIndex = 1;
            this.siticonePanel1.TabStop = true;
            this.siticonePanel1.TrackSystemTheme = false;
            this.siticonePanel1.UseBorderGradient = true;
            this.siticonePanel1.UseMultiGradient = false;
            this.siticonePanel1.UsePatternTexture = false;
            this.siticonePanel1.UseRadialGradient = false;
            // 
            // btnCart
            // 
            this.btnCart.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnCart.AccessibleName = "Cart";
            this.btnCart.AutoSizeBasedOnText = false;
            this.btnCart.BackColor = System.Drawing.Color.Transparent;
            this.btnCart.BadgeBackColor = System.Drawing.Color.Black;
            this.btnCart.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnCart.BadgeValue = 0;
            this.btnCart.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnCart.BorderColor = System.Drawing.Color.Tan;
            this.btnCart.BorderWidth = 2;
            this.btnCart.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnCart.ButtonImage = null;
            this.btnCart.ButtonTextLeftPadding = 0;
            this.btnCart.CanBeep = true;
            this.btnCart.CanGlow = true;
            this.btnCart.CanShake = true;
            this.btnCart.ContextMenuStripEx = null;
            this.btnCart.CornerRadiusBottomLeft = 19;
            this.btnCart.CornerRadiusBottomRight = 19;
            this.btnCart.CornerRadiusTopLeft = 19;
            this.btnCart.CornerRadiusTopRight = 19;
            this.btnCart.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnCart.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnCart.EnableLongPress = false;
            this.btnCart.EnableRippleEffect = true;
            this.btnCart.EnableShadow = false;
            this.btnCart.EnableTextWrapping = false;
            this.btnCart.Font = new System.Drawing.Font("Times New Roman", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCart.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnCart.GlowIntensity = 100;
            this.btnCart.GlowRadius = 20F;
            this.btnCart.GradientBackground = false;
            this.btnCart.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnCart.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnCart.HintText = null;
            this.btnCart.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnCart.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCart.HoverTextColor = System.Drawing.Color.White;
            this.btnCart.HoverTransitionDuration = 250;
            this.btnCart.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCart.ImagePadding = 5;
            this.btnCart.ImageSize = new System.Drawing.Size(16, 16);
            this.btnCart.IsRadial = true;
            this.btnCart.IsReadOnly = false;
            this.btnCart.IsToggleButton = false;
            this.btnCart.IsToggled = false;
            this.btnCart.Location = new System.Drawing.Point(49, 242);
            this.btnCart.LongPressDurationMS = 1000;
            this.btnCart.Name = "btnCart";
            this.btnCart.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCart.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnCart.ParticleCount = 15;
            this.btnCart.PressAnimationScale = 0.97F;
            this.btnCart.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnCart.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCart.PressTransitionDuration = 150;
            this.btnCart.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnCart.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnCart.RippleOpacity = 0.2F;
            this.btnCart.RippleRadiusMultiplier = 0.6F;
            this.btnCart.ShadowBlur = 6;
            this.btnCart.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnCart.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnCart.ShakeDuration = 500;
            this.btnCart.ShakeIntensity = 5;
            this.btnCart.Size = new System.Drawing.Size(154, 42);
            this.btnCart.TabIndex = 14;
            this.btnCart.Text = "Cart";
            this.btnCart.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCart.TextColor = System.Drawing.Color.Black;
            this.btnCart.TooltipText = null;
            this.btnCart.UseAdvancedRendering = true;
            this.btnCart.UseParticles = false;
            this.btnCart.Click += new System.EventHandler(this.btnCart_Click);
            // 
            // btnLogout
            // 
            this.btnLogout.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnLogout.AccessibleName = "Log out";
            this.btnLogout.AutoSizeBasedOnText = false;
            this.btnLogout.BackColor = System.Drawing.Color.Transparent;
            this.btnLogout.BadgeBackColor = System.Drawing.Color.Black;
            this.btnLogout.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnLogout.BadgeValue = 0;
            this.btnLogout.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnLogout.BorderColor = System.Drawing.Color.Tan;
            this.btnLogout.BorderWidth = 2;
            this.btnLogout.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnLogout.ButtonImage = null;
            this.btnLogout.ButtonTextLeftPadding = 0;
            this.btnLogout.CanBeep = true;
            this.btnLogout.CanGlow = true;
            this.btnLogout.CanShake = true;
            this.btnLogout.ContextMenuStripEx = null;
            this.btnLogout.CornerRadiusBottomLeft = 19;
            this.btnLogout.CornerRadiusBottomRight = 19;
            this.btnLogout.CornerRadiusTopLeft = 19;
            this.btnLogout.CornerRadiusTopRight = 19;
            this.btnLogout.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnLogout.EnableLongPress = false;
            this.btnLogout.EnableRippleEffect = true;
            this.btnLogout.EnableShadow = false;
            this.btnLogout.EnableTextWrapping = false;
            this.btnLogout.Font = new System.Drawing.Font("Times New Roman", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogout.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnLogout.GlowIntensity = 100;
            this.btnLogout.GlowRadius = 20F;
            this.btnLogout.GradientBackground = false;
            this.btnLogout.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnLogout.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnLogout.HintText = null;
            this.btnLogout.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnLogout.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnLogout.HoverTextColor = System.Drawing.Color.White;
            this.btnLogout.HoverTransitionDuration = 250;
            this.btnLogout.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.ImagePadding = 5;
            this.btnLogout.ImageSize = new System.Drawing.Size(16, 16);
            this.btnLogout.IsRadial = true;
            this.btnLogout.IsReadOnly = false;
            this.btnLogout.IsToggleButton = false;
            this.btnLogout.IsToggled = false;
            this.btnLogout.Location = new System.Drawing.Point(50, 462);
            this.btnLogout.LongPressDurationMS = 1000;
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnLogout.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnLogout.ParticleCount = 15;
            this.btnLogout.PressAnimationScale = 0.97F;
            this.btnLogout.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnLogout.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnLogout.PressTransitionDuration = 150;
            this.btnLogout.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnLogout.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnLogout.RippleOpacity = 0.2F;
            this.btnLogout.RippleRadiusMultiplier = 0.6F;
            this.btnLogout.ShadowBlur = 6;
            this.btnLogout.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnLogout.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnLogout.ShakeDuration = 500;
            this.btnLogout.ShakeIntensity = 5;
            this.btnLogout.Size = new System.Drawing.Size(154, 42);
            this.btnLogout.TabIndex = 4;
            this.btnLogout.Text = "Log out";
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogout.TextColor = System.Drawing.Color.Black;
            this.btnLogout.TooltipText = null;
            this.btnLogout.UseAdvancedRendering = true;
            this.btnLogout.UseParticles = false;
            this.btnLogout.Click += new System.EventHandler(this.siticoneButton7_Click);
            // 
            // siticoneLabel1
            // 
            this.siticoneLabel1.BackColor = System.Drawing.Color.Transparent;
            this.siticoneLabel1.Font = new System.Drawing.Font("Times New Roman", 26.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.siticoneLabel1.Location = new System.Drawing.Point(70, 69);
            this.siticoneLabel1.Name = "siticoneLabel1";
            this.siticoneLabel1.Size = new System.Drawing.Size(119, 48);
            this.siticoneLabel1.TabIndex = 3;
            this.siticoneLabel1.Text = "Cafero";
            // 
            // btnMenu
            // 
            this.btnMenu.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnMenu.AccessibleName = "Menu";
            this.btnMenu.AutoSizeBasedOnText = false;
            this.btnMenu.BackColor = System.Drawing.Color.Transparent;
            this.btnMenu.BadgeBackColor = System.Drawing.Color.Black;
            this.btnMenu.BadgeFont = new System.Drawing.Font("Times New Roman", 9.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMenu.BadgeValue = 0;
            this.btnMenu.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnMenu.BorderColor = System.Drawing.Color.Tan;
            this.btnMenu.BorderWidth = 2;
            this.btnMenu.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnMenu.ButtonImage = null;
            this.btnMenu.ButtonTextLeftPadding = 0;
            this.btnMenu.CanBeep = true;
            this.btnMenu.CanGlow = true;
            this.btnMenu.CanShake = true;
            this.btnMenu.CenterTextAndBadgeTogether = false;
            this.btnMenu.ContextMenuStripEx = null;
            this.btnMenu.CornerRadiusBottomLeft = 19;
            this.btnMenu.CornerRadiusBottomRight = 19;
            this.btnMenu.CornerRadiusTopLeft = 19;
            this.btnMenu.CornerRadiusTopRight = 19;
            this.btnMenu.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnMenu.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnMenu.EnableLongPress = false;
            this.btnMenu.EnableRippleEffect = true;
            this.btnMenu.EnableShadow = false;
            this.btnMenu.EnableTextWrapping = false;
            this.btnMenu.Font = new System.Drawing.Font("Times New Roman", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMenu.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnMenu.GlowIntensity = 100;
            this.btnMenu.GlowRadius = 20F;
            this.btnMenu.GradientBackground = false;
            this.btnMenu.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnMenu.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnMenu.HintText = null;
            this.btnMenu.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnMenu.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.HoverTextColor = System.Drawing.Color.White;
            this.btnMenu.HoverTransitionDuration = 250;
            this.btnMenu.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMenu.ImagePadding = 5;
            this.btnMenu.ImageSize = new System.Drawing.Size(16, 16);
            this.btnMenu.IsRadial = true;
            this.btnMenu.IsReadOnly = false;
            this.btnMenu.IsToggleButton = false;
            this.btnMenu.IsToggled = false;
            this.btnMenu.Location = new System.Drawing.Point(50, 169);
            this.btnMenu.LongPressDurationMS = 1000;
            this.btnMenu.Name = "btnMenu";
            this.btnMenu.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnMenu.ParticleCount = 15;
            this.btnMenu.PressAnimationScale = 0.97F;
            this.btnMenu.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnMenu.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMenu.PressTransitionDuration = 150;
            this.btnMenu.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnMenu.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnMenu.RippleOpacity = 0.2F;
            this.btnMenu.RippleRadiusMultiplier = 0.6F;
            this.btnMenu.ShadowBlur = 6;
            this.btnMenu.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnMenu.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnMenu.ShakeDuration = 500;
            this.btnMenu.ShakeIntensity = 5;
            this.btnMenu.Size = new System.Drawing.Size(154, 42);
            this.btnMenu.TabIndex = 2;
            this.btnMenu.Text = "Menu";
            this.btnMenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMenu.TextColor = System.Drawing.Color.Black;
            this.btnMenu.TooltipText = null;
            this.btnMenu.UseAdvancedRendering = true;
            this.btnMenu.UseParticles = false;
            // 
            // btnInventory
            // 
            this.btnInventory.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnInventory.AccessibleName = "Inventory";
            this.btnInventory.AutoSizeBasedOnText = false;
            this.btnInventory.BackColor = System.Drawing.Color.Transparent;
            this.btnInventory.BadgeBackColor = System.Drawing.Color.Black;
            this.btnInventory.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnInventory.BadgeValue = 0;
            this.btnInventory.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnInventory.BorderColor = System.Drawing.Color.Tan;
            this.btnInventory.BorderWidth = 2;
            this.btnInventory.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnInventory.ButtonImage = null;
            this.btnInventory.ButtonTextLeftPadding = 0;
            this.btnInventory.CanBeep = true;
            this.btnInventory.CanGlow = true;
            this.btnInventory.CanShake = true;
            this.btnInventory.ContextMenuStripEx = null;
            this.btnInventory.CornerRadiusBottomLeft = 19;
            this.btnInventory.CornerRadiusBottomRight = 19;
            this.btnInventory.CornerRadiusTopLeft = 19;
            this.btnInventory.CornerRadiusTopRight = 19;
            this.btnInventory.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnInventory.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnInventory.EnableLongPress = false;
            this.btnInventory.EnableRippleEffect = true;
            this.btnInventory.EnableShadow = false;
            this.btnInventory.EnableTextWrapping = false;
            this.btnInventory.Font = new System.Drawing.Font("Times New Roman", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInventory.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(170)))), ((int)(((byte)(255)))));
            this.btnInventory.GlowIntensity = 100;
            this.btnInventory.GlowRadius = 20F;
            this.btnInventory.GradientBackground = false;
            this.btnInventory.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnInventory.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnInventory.HintText = null;
            this.btnInventory.HoverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(172)))), ((int)(((byte)(194)))));
            this.btnInventory.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.HoverTextColor = System.Drawing.Color.White;
            this.btnInventory.HoverTransitionDuration = 250;
            this.btnInventory.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInventory.ImagePadding = 5;
            this.btnInventory.ImageSize = new System.Drawing.Size(16, 16);
            this.btnInventory.IsRadial = true;
            this.btnInventory.IsReadOnly = false;
            this.btnInventory.IsToggleButton = false;
            this.btnInventory.IsToggled = false;
            this.btnInventory.Location = new System.Drawing.Point(50, 315);
            this.btnInventory.LongPressDurationMS = 1000;
            this.btnInventory.Name = "btnInventory";
            this.btnInventory.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnInventory.ParticleCount = 15;
            this.btnInventory.PressAnimationScale = 0.97F;
            this.btnInventory.PressedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(152)))), ((int)(((byte)(174)))));
            this.btnInventory.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnInventory.PressTransitionDuration = 150;
            this.btnInventory.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnInventory.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnInventory.RippleOpacity = 0.2F;
            this.btnInventory.RippleRadiusMultiplier = 0.6F;
            this.btnInventory.ShadowBlur = 6;
            this.btnInventory.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInventory.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnInventory.ShakeDuration = 500;
            this.btnInventory.ShakeIntensity = 5;
            this.btnInventory.Size = new System.Drawing.Size(154, 42);
            this.btnInventory.TabIndex = 1;
            this.btnInventory.Text = "Inventory";
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInventory.TextColor = System.Drawing.Color.Black;
            this.btnInventory.TooltipText = null;
            this.btnInventory.UseAdvancedRendering = true;
            this.btnInventory.UseParticles = false;
            // 
            // btnSales
            // 
            this.btnSales.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnSales.AccessibleName = "Analytics";
            this.btnSales.AutoSizeBasedOnText = false;
            this.btnSales.BackColor = System.Drawing.Color.Transparent;
            this.btnSales.BadgeBackColor = System.Drawing.Color.Black;
            this.btnSales.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnSales.BadgeValue = 0;
            this.btnSales.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnSales.BorderColor = System.Drawing.Color.Tan;
            this.btnSales.BorderWidth = 2;
            this.btnSales.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnSales.ButtonImage = null;
            this.btnSales.ButtonTextLeftPadding = 0;
            this.btnSales.CanBeep = true;
            this.btnSales.CanGlow = true;
            this.btnSales.CanShake = true;
            this.btnSales.ContextMenuStripEx = null;
            this.btnSales.CornerRadiusBottomLeft = 19;
            this.btnSales.CornerRadiusBottomRight = 19;
            this.btnSales.CornerRadiusTopLeft = 19;
            this.btnSales.CornerRadiusTopRight = 19;
            this.btnSales.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnSales.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnSales.EnableLongPress = false;
            this.btnSales.EnableRippleEffect = true;
            this.btnSales.EnableShadow = false;
            this.btnSales.EnableTextWrapping = false;
            this.btnSales.Font = new System.Drawing.Font("Times New Roman", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSales.GlowColor = System.Drawing.Color.Transparent;
            this.btnSales.GlowIntensity = 100;
            this.btnSales.GlowRadius = 20F;
            this.btnSales.GradientBackground = false;
            this.btnSales.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnSales.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnSales.HintText = null;
            this.btnSales.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnSales.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.HoverTextColor = System.Drawing.Color.White;
            this.btnSales.HoverTransitionDuration = 250;
            this.btnSales.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSales.ImagePadding = 5;
            this.btnSales.ImageSize = new System.Drawing.Size(16, 16);
            this.btnSales.IsRadial = true;
            this.btnSales.IsReadOnly = false;
            this.btnSales.IsToggleButton = false;
            this.btnSales.IsToggled = false;
            this.btnSales.Location = new System.Drawing.Point(50, 387);
            this.btnSales.LongPressDurationMS = 1000;
            this.btnSales.Name = "btnSales";
            this.btnSales.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnSales.ParticleCount = 15;
            this.btnSales.PressAnimationScale = 0.97F;
            this.btnSales.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnSales.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSales.PressTransitionDuration = 150;
            this.btnSales.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnSales.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnSales.RippleOpacity = 1F;
            this.btnSales.RippleRadiusMultiplier = 0.6F;
            this.btnSales.ShadowBlur = 6;
            this.btnSales.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnSales.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnSales.ShakeDuration = 500;
            this.btnSales.ShakeIntensity = 5;
            this.btnSales.Size = new System.Drawing.Size(154, 42);
            this.btnSales.TabIndex = 0;
            this.btnSales.Text = "Analytics";
            this.btnSales.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSales.TextColor = System.Drawing.Color.Black;
            this.btnSales.TooltipText = null;
            this.btnSales.UseAdvancedRendering = true;
            this.btnSales.UseParticles = false;
            this.btnSales.Click += new System.EventHandler(this.btnSales_Click);
            // 
            // btnCoffee
            // 
            this.btnCoffee.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnCoffee.AccessibleName = "COFFEE";
            this.btnCoffee.AutoSizeBasedOnText = false;
            this.btnCoffee.BackColor = System.Drawing.Color.Transparent;
            this.btnCoffee.BadgeBackColor = System.Drawing.Color.Black;
            this.btnCoffee.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnCoffee.BadgeValue = 0;
            this.btnCoffee.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnCoffee.BorderColor = System.Drawing.Color.Tan;
            this.btnCoffee.BorderWidth = 2;
            this.btnCoffee.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnCoffee.ButtonImage = null;
            this.btnCoffee.ButtonTextLeftPadding = 0;
            this.btnCoffee.CanBeep = true;
            this.btnCoffee.CanGlow = true;
            this.btnCoffee.CanShake = true;
            this.btnCoffee.ContextMenuStripEx = null;
            this.btnCoffee.CornerRadiusBottomLeft = 23;
            this.btnCoffee.CornerRadiusBottomRight = 23;
            this.btnCoffee.CornerRadiusTopLeft = 23;
            this.btnCoffee.CornerRadiusTopRight = 23;
            this.btnCoffee.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnCoffee.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnCoffee.EnableLongPress = false;
            this.btnCoffee.EnableRippleEffect = true;
            this.btnCoffee.EnableShadow = false;
            this.btnCoffee.EnableTextWrapping = false;
            this.btnCoffee.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCoffee.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnCoffee.GlowIntensity = 100;
            this.btnCoffee.GlowRadius = 20F;
            this.btnCoffee.GradientBackground = false;
            this.btnCoffee.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnCoffee.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnCoffee.HintText = null;
            this.btnCoffee.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnCoffee.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCoffee.HoverTextColor = System.Drawing.Color.Black;
            this.btnCoffee.HoverTransitionDuration = 250;
            this.btnCoffee.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCoffee.ImagePadding = 5;
            this.btnCoffee.ImageSize = new System.Drawing.Size(16, 16);
            this.btnCoffee.IsRadial = true;
            this.btnCoffee.IsReadOnly = false;
            this.btnCoffee.IsToggleButton = false;
            this.btnCoffee.IsToggled = false;
            this.btnCoffee.Location = new System.Drawing.Point(228, 60);
            this.btnCoffee.LongPressDurationMS = 1000;
            this.btnCoffee.Name = "btnCoffee";
            this.btnCoffee.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCoffee.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnCoffee.ParticleCount = 15;
            this.btnCoffee.PressAnimationScale = 0.97F;
            this.btnCoffee.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnCoffee.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnCoffee.PressTransitionDuration = 150;
            this.btnCoffee.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnCoffee.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnCoffee.RippleRadiusMultiplier = 0.6F;
            this.btnCoffee.ShadowBlur = 5;
            this.btnCoffee.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnCoffee.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnCoffee.ShakeDuration = 500;
            this.btnCoffee.ShakeIntensity = 5;
            this.btnCoffee.Size = new System.Drawing.Size(190, 50);
            this.btnCoffee.TabIndex = 2;
            this.btnCoffee.Text = "COFFEE";
            this.btnCoffee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCoffee.TextColor = System.Drawing.Color.Black;
            this.btnCoffee.TooltipText = null;
            this.btnCoffee.UseAdvancedRendering = true;
            this.btnCoffee.UseParticles = false;
            this.btnCoffee.Click += new System.EventHandler(this.siticoneButton1_Click);
            // 
            // btnMilktea
            // 
            this.btnMilktea.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnMilktea.AccessibleName = "MILKTEA";
            this.btnMilktea.AutoSizeBasedOnText = false;
            this.btnMilktea.BackColor = System.Drawing.Color.Transparent;
            this.btnMilktea.BadgeBackColor = System.Drawing.Color.Black;
            this.btnMilktea.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnMilktea.BadgeValue = 0;
            this.btnMilktea.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnMilktea.BorderColor = System.Drawing.Color.Tan;
            this.btnMilktea.BorderWidth = 2;
            this.btnMilktea.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnMilktea.ButtonImage = null;
            this.btnMilktea.ButtonTextLeftPadding = 0;
            this.btnMilktea.CanBeep = true;
            this.btnMilktea.CanGlow = true;
            this.btnMilktea.CanShake = true;
            this.btnMilktea.ContextMenuStripEx = null;
            this.btnMilktea.CornerRadiusBottomLeft = 23;
            this.btnMilktea.CornerRadiusBottomRight = 23;
            this.btnMilktea.CornerRadiusTopLeft = 23;
            this.btnMilktea.CornerRadiusTopRight = 23;
            this.btnMilktea.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnMilktea.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnMilktea.EnableLongPress = false;
            this.btnMilktea.EnableRippleEffect = true;
            this.btnMilktea.EnableShadow = false;
            this.btnMilktea.EnableTextWrapping = false;
            this.btnMilktea.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMilktea.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnMilktea.GlowIntensity = 100;
            this.btnMilktea.GlowRadius = 20F;
            this.btnMilktea.GradientBackground = false;
            this.btnMilktea.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnMilktea.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnMilktea.HintText = null;
            this.btnMilktea.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnMilktea.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMilktea.HoverTextColor = System.Drawing.Color.Black;
            this.btnMilktea.HoverTransitionDuration = 250;
            this.btnMilktea.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMilktea.ImagePadding = 5;
            this.btnMilktea.ImageSize = new System.Drawing.Size(16, 16);
            this.btnMilktea.IsRadial = true;
            this.btnMilktea.IsReadOnly = false;
            this.btnMilktea.IsToggleButton = false;
            this.btnMilktea.IsToggled = false;
            this.btnMilktea.Location = new System.Drawing.Point(510, 60);
            this.btnMilktea.LongPressDurationMS = 1000;
            this.btnMilktea.Name = "btnMilktea";
            this.btnMilktea.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMilktea.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnMilktea.ParticleCount = 15;
            this.btnMilktea.PressAnimationScale = 0.97F;
            this.btnMilktea.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnMilktea.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnMilktea.PressTransitionDuration = 150;
            this.btnMilktea.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnMilktea.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnMilktea.RippleRadiusMultiplier = 0.6F;
            this.btnMilktea.ShadowBlur = 5;
            this.btnMilktea.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnMilktea.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnMilktea.ShakeDuration = 500;
            this.btnMilktea.ShakeIntensity = 5;
            this.btnMilktea.Size = new System.Drawing.Size(190, 50);
            this.btnMilktea.TabIndex = 8;
            this.btnMilktea.Text = "MILKTEA";
            this.btnMilktea.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMilktea.TextColor = System.Drawing.Color.Black;
            this.btnMilktea.TooltipText = null;
            this.btnMilktea.UseAdvancedRendering = true;
            this.btnMilktea.UseParticles = false;
            this.btnMilktea.Click += new System.EventHandler(this.btnMilktea_Click);
            // 
            // btnFruitTea
            // 
            this.btnFruitTea.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnFruitTea.AccessibleName = "FRUIT TEA";
            this.btnFruitTea.AutoSizeBasedOnText = false;
            this.btnFruitTea.BackColor = System.Drawing.Color.Transparent;
            this.btnFruitTea.BadgeBackColor = System.Drawing.Color.Black;
            this.btnFruitTea.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnFruitTea.BadgeValue = 0;
            this.btnFruitTea.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnFruitTea.BorderColor = System.Drawing.Color.Tan;
            this.btnFruitTea.BorderWidth = 2;
            this.btnFruitTea.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnFruitTea.ButtonImage = null;
            this.btnFruitTea.ButtonTextLeftPadding = 0;
            this.btnFruitTea.CanBeep = true;
            this.btnFruitTea.CanGlow = true;
            this.btnFruitTea.CanShake = true;
            this.btnFruitTea.ContextMenuStripEx = null;
            this.btnFruitTea.CornerRadiusBottomLeft = 23;
            this.btnFruitTea.CornerRadiusBottomRight = 23;
            this.btnFruitTea.CornerRadiusTopLeft = 23;
            this.btnFruitTea.CornerRadiusTopRight = 23;
            this.btnFruitTea.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnFruitTea.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnFruitTea.EnableLongPress = false;
            this.btnFruitTea.EnableRippleEffect = true;
            this.btnFruitTea.EnableShadow = false;
            this.btnFruitTea.EnableTextWrapping = false;
            this.btnFruitTea.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFruitTea.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnFruitTea.GlowIntensity = 100;
            this.btnFruitTea.GlowRadius = 20F;
            this.btnFruitTea.GradientBackground = false;
            this.btnFruitTea.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnFruitTea.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnFruitTea.HintText = null;
            this.btnFruitTea.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnFruitTea.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnFruitTea.HoverTextColor = System.Drawing.Color.Black;
            this.btnFruitTea.HoverTransitionDuration = 250;
            this.btnFruitTea.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFruitTea.ImagePadding = 5;
            this.btnFruitTea.ImageSize = new System.Drawing.Size(16, 16);
            this.btnFruitTea.IsRadial = true;
            this.btnFruitTea.IsReadOnly = false;
            this.btnFruitTea.IsToggleButton = false;
            this.btnFruitTea.IsToggled = false;
            this.btnFruitTea.Location = new System.Drawing.Point(790, 62);
            this.btnFruitTea.LongPressDurationMS = 1000;
            this.btnFruitTea.Name = "btnFruitTea";
            this.btnFruitTea.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnFruitTea.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnFruitTea.ParticleCount = 15;
            this.btnFruitTea.PressAnimationScale = 0.97F;
            this.btnFruitTea.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnFruitTea.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnFruitTea.PressTransitionDuration = 150;
            this.btnFruitTea.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnFruitTea.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnFruitTea.RippleRadiusMultiplier = 0.6F;
            this.btnFruitTea.ShadowBlur = 5;
            this.btnFruitTea.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnFruitTea.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnFruitTea.ShakeDuration = 500;
            this.btnFruitTea.ShakeIntensity = 5;
            this.btnFruitTea.Size = new System.Drawing.Size(190, 50);
            this.btnFruitTea.TabIndex = 9;
            this.btnFruitTea.Text = "FRUIT TEA";
            this.btnFruitTea.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFruitTea.TextColor = System.Drawing.Color.Black;
            this.btnFruitTea.TooltipText = null;
            this.btnFruitTea.UseAdvancedRendering = true;
            this.btnFruitTea.UseParticles = false;
            this.btnFruitTea.Click += new System.EventHandler(this.btnFruitTea_Click);
            // 
            // btnRiceMeal
            // 
            this.btnRiceMeal.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnRiceMeal.AccessibleName = "RICE MEAL";
            this.btnRiceMeal.AutoSizeBasedOnText = false;
            this.btnRiceMeal.BackColor = System.Drawing.Color.Transparent;
            this.btnRiceMeal.BadgeBackColor = System.Drawing.Color.Black;
            this.btnRiceMeal.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnRiceMeal.BadgeValue = 0;
            this.btnRiceMeal.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnRiceMeal.BorderColor = System.Drawing.Color.Tan;
            this.btnRiceMeal.BorderWidth = 2;
            this.btnRiceMeal.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnRiceMeal.ButtonImage = null;
            this.btnRiceMeal.ButtonTextLeftPadding = 0;
            this.btnRiceMeal.CanBeep = true;
            this.btnRiceMeal.CanGlow = true;
            this.btnRiceMeal.CanShake = true;
            this.btnRiceMeal.ContextMenuStripEx = null;
            this.btnRiceMeal.CornerRadiusBottomLeft = 23;
            this.btnRiceMeal.CornerRadiusBottomRight = 23;
            this.btnRiceMeal.CornerRadiusTopLeft = 23;
            this.btnRiceMeal.CornerRadiusTopRight = 23;
            this.btnRiceMeal.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnRiceMeal.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnRiceMeal.EnableLongPress = false;
            this.btnRiceMeal.EnableRippleEffect = true;
            this.btnRiceMeal.EnableShadow = false;
            this.btnRiceMeal.EnableTextWrapping = false;
            this.btnRiceMeal.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRiceMeal.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnRiceMeal.GlowIntensity = 100;
            this.btnRiceMeal.GlowRadius = 20F;
            this.btnRiceMeal.GradientBackground = false;
            this.btnRiceMeal.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnRiceMeal.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnRiceMeal.HintText = null;
            this.btnRiceMeal.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnRiceMeal.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnRiceMeal.HoverTextColor = System.Drawing.Color.Black;
            this.btnRiceMeal.HoverTransitionDuration = 250;
            this.btnRiceMeal.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRiceMeal.ImagePadding = 5;
            this.btnRiceMeal.ImageSize = new System.Drawing.Size(16, 16);
            this.btnRiceMeal.IsRadial = true;
            this.btnRiceMeal.IsReadOnly = false;
            this.btnRiceMeal.IsToggleButton = false;
            this.btnRiceMeal.IsToggled = false;
            this.btnRiceMeal.Location = new System.Drawing.Point(1073, 62);
            this.btnRiceMeal.LongPressDurationMS = 1000;
            this.btnRiceMeal.Name = "btnRiceMeal";
            this.btnRiceMeal.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnRiceMeal.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnRiceMeal.ParticleCount = 15;
            this.btnRiceMeal.PressAnimationScale = 0.97F;
            this.btnRiceMeal.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnRiceMeal.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnRiceMeal.PressTransitionDuration = 150;
            this.btnRiceMeal.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnRiceMeal.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnRiceMeal.RippleRadiusMultiplier = 0.6F;
            this.btnRiceMeal.ShadowBlur = 5;
            this.btnRiceMeal.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnRiceMeal.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnRiceMeal.ShakeDuration = 500;
            this.btnRiceMeal.ShakeIntensity = 5;
            this.btnRiceMeal.Size = new System.Drawing.Size(190, 50);
            this.btnRiceMeal.TabIndex = 10;
            this.btnRiceMeal.Text = "RICE MEAL";
            this.btnRiceMeal.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRiceMeal.TextColor = System.Drawing.Color.Black;
            this.btnRiceMeal.TooltipText = null;
            this.btnRiceMeal.UseAdvancedRendering = true;
            this.btnRiceMeal.UseParticles = false;
            this.btnRiceMeal.Click += new System.EventHandler(this.btnRiceMeal_Click);
            // 
            // btnPastry
            // 
            this.btnPastry.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnPastry.AccessibleName = "PASTRY";
            this.btnPastry.AutoSizeBasedOnText = false;
            this.btnPastry.BackColor = System.Drawing.Color.Transparent;
            this.btnPastry.BadgeBackColor = System.Drawing.Color.Black;
            this.btnPastry.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnPastry.BadgeValue = 0;
            this.btnPastry.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnPastry.BorderColor = System.Drawing.Color.Tan;
            this.btnPastry.BorderWidth = 2;
            this.btnPastry.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnPastry.ButtonImage = null;
            this.btnPastry.ButtonTextLeftPadding = 0;
            this.btnPastry.CanBeep = true;
            this.btnPastry.CanGlow = true;
            this.btnPastry.CanShake = true;
            this.btnPastry.ContextMenuStripEx = null;
            this.btnPastry.CornerRadiusBottomLeft = 23;
            this.btnPastry.CornerRadiusBottomRight = 23;
            this.btnPastry.CornerRadiusTopLeft = 23;
            this.btnPastry.CornerRadiusTopRight = 23;
            this.btnPastry.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnPastry.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnPastry.EnableLongPress = false;
            this.btnPastry.EnableRippleEffect = true;
            this.btnPastry.EnableShadow = false;
            this.btnPastry.EnableTextWrapping = false;
            this.btnPastry.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPastry.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnPastry.GlowIntensity = 100;
            this.btnPastry.GlowRadius = 20F;
            this.btnPastry.GradientBackground = false;
            this.btnPastry.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnPastry.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnPastry.HintText = null;
            this.btnPastry.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnPastry.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnPastry.HoverTextColor = System.Drawing.Color.Black;
            this.btnPastry.HoverTransitionDuration = 250;
            this.btnPastry.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPastry.ImagePadding = 5;
            this.btnPastry.ImageSize = new System.Drawing.Size(16, 16);
            this.btnPastry.IsRadial = true;
            this.btnPastry.IsReadOnly = false;
            this.btnPastry.IsToggleButton = false;
            this.btnPastry.IsToggled = false;
            this.btnPastry.Location = new System.Drawing.Point(1364, 62);
            this.btnPastry.LongPressDurationMS = 1000;
            this.btnPastry.Name = "btnPastry";
            this.btnPastry.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnPastry.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnPastry.ParticleCount = 15;
            this.btnPastry.PressAnimationScale = 0.97F;
            this.btnPastry.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnPastry.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnPastry.PressTransitionDuration = 150;
            this.btnPastry.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnPastry.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnPastry.RippleRadiusMultiplier = 0.6F;
            this.btnPastry.ShadowBlur = 5;
            this.btnPastry.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnPastry.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnPastry.ShakeDuration = 500;
            this.btnPastry.ShakeIntensity = 5;
            this.btnPastry.Size = new System.Drawing.Size(190, 50);
            this.btnPastry.TabIndex = 11;
            this.btnPastry.Text = "PASTRY";
            this.btnPastry.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPastry.TextColor = System.Drawing.Color.Black;
            this.btnPastry.TooltipText = null;
            this.btnPastry.UseAdvancedRendering = true;
            this.btnPastry.UseParticles = false;
            this.btnPastry.Click += new System.EventHandler(this.btnPastry_Click);
            // 
            // btnSnacksPasta
            // 
            this.btnSnacksPasta.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard" +
    "";
            this.btnSnacksPasta.AccessibleName = "SNACKS AND PASTA";
            this.btnSnacksPasta.AutoSizeBasedOnText = false;
            this.btnSnacksPasta.BackColor = System.Drawing.Color.Transparent;
            this.btnSnacksPasta.BadgeBackColor = System.Drawing.Color.Black;
            this.btnSnacksPasta.BadgeFont = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.btnSnacksPasta.BadgeValue = 0;
            this.btnSnacksPasta.BadgeValueForeColor = System.Drawing.Color.White;
            this.btnSnacksPasta.BorderColor = System.Drawing.Color.Tan;
            this.btnSnacksPasta.BorderWidth = 2;
            this.btnSnacksPasta.ButtonBackColor = System.Drawing.Color.Tan;
            this.btnSnacksPasta.ButtonImage = null;
            this.btnSnacksPasta.ButtonTextLeftPadding = 0;
            this.btnSnacksPasta.CanBeep = true;
            this.btnSnacksPasta.CanGlow = true;
            this.btnSnacksPasta.CanShake = true;
            this.btnSnacksPasta.ContextMenuStripEx = null;
            this.btnSnacksPasta.CornerRadiusBottomLeft = 23;
            this.btnSnacksPasta.CornerRadiusBottomRight = 23;
            this.btnSnacksPasta.CornerRadiusTopLeft = 23;
            this.btnSnacksPasta.CornerRadiusTopRight = 23;
            this.btnSnacksPasta.CustomCursor = System.Windows.Forms.Cursors.Default;
            this.btnSnacksPasta.DisabledTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(150)))), ((int)(((byte)(150)))));
            this.btnSnacksPasta.EnableLongPress = false;
            this.btnSnacksPasta.EnableRippleEffect = true;
            this.btnSnacksPasta.EnableShadow = false;
            this.btnSnacksPasta.EnableTextWrapping = false;
            this.btnSnacksPasta.Font = new System.Drawing.Font("Times New Roman", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSnacksPasta.GlowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnSnacksPasta.GlowIntensity = 100;
            this.btnSnacksPasta.GlowRadius = 20F;
            this.btnSnacksPasta.GradientBackground = false;
            this.btnSnacksPasta.GradientColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(227)))), ((int)(((byte)(64)))));
            this.btnSnacksPasta.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            this.btnSnacksPasta.HintText = null;
            this.btnSnacksPasta.HoverBackColor = System.Drawing.Color.Transparent;
            this.btnSnacksPasta.HoverFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSnacksPasta.HoverTextColor = System.Drawing.Color.Black;
            this.btnSnacksPasta.HoverTransitionDuration = 250;
            this.btnSnacksPasta.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSnacksPasta.ImagePadding = 5;
            this.btnSnacksPasta.ImageSize = new System.Drawing.Size(16, 16);
            this.btnSnacksPasta.IsRadial = true;
            this.btnSnacksPasta.IsReadOnly = false;
            this.btnSnacksPasta.IsToggleButton = false;
            this.btnSnacksPasta.IsToggled = false;
            this.btnSnacksPasta.Location = new System.Drawing.Point(1657, 60);
            this.btnSnacksPasta.LongPressDurationMS = 1000;
            this.btnSnacksPasta.Name = "btnSnacksPasta";
            this.btnSnacksPasta.NormalFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSnacksPasta.ParticleColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnSnacksPasta.ParticleCount = 15;
            this.btnSnacksPasta.PressAnimationScale = 0.97F;
            this.btnSnacksPasta.PressedBackColor = System.Drawing.Color.Transparent;
            this.btnSnacksPasta.PressedFontStyle = System.Drawing.FontStyle.Regular;
            this.btnSnacksPasta.PressTransitionDuration = 150;
            this.btnSnacksPasta.ReadOnlyTextColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnSnacksPasta.RippleColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
            this.btnSnacksPasta.RippleRadiusMultiplier = 0.6F;
            this.btnSnacksPasta.ShadowBlur = 5;
            this.btnSnacksPasta.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnSnacksPasta.ShadowOffset = new System.Drawing.Point(0, 2);
            this.btnSnacksPasta.ShakeDuration = 500;
            this.btnSnacksPasta.ShakeIntensity = 5;
            this.btnSnacksPasta.Size = new System.Drawing.Size(190, 50);
            this.btnSnacksPasta.TabIndex = 12;
            this.btnSnacksPasta.Text = "SNACKS AND PASTA";
            this.btnSnacksPasta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSnacksPasta.TextColor = System.Drawing.Color.Black;
            this.btnSnacksPasta.TooltipText = null;
            this.btnSnacksPasta.UseAdvancedRendering = true;
            this.btnSnacksPasta.UseParticles = false;
            // 
            // Menu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(1924, 1061);
            this.Controls.Add(this.btnSnacksPasta);
            this.Controls.Add(this.btnPastry);
            this.Controls.Add(this.btnRiceMeal);
            this.Controls.Add(this.btnFruitTea);
            this.Controls.Add(this.btnMilktea);
            this.Controls.Add(this.btnCoffee);
            this.Controls.Add(this.siticonePanel1);
            this.ForeColor = System.Drawing.Color.Black;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Menu";
            this.Text = "Dashboard";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.Menu_Load);
            this.siticonePanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private SiticoneNetFrameworkUI.SiticonePanel siticonePanel1;
        private SiticoneNetFrameworkUI.SiticoneLabel siticoneLabel1;
        private SiticoneNetFrameworkUI.SiticoneButton btnInventory;
        private SiticoneNetFrameworkUI.SiticoneButton btnSales;
        private SiticoneNetFrameworkUI.SiticoneButton btnCoffee;
        private SiticoneNetFrameworkUI.SiticoneButton btnLogout;
        private SiticoneNetFrameworkUI.SiticoneButton btnMenu;
        private SiticoneNetFrameworkUI.SiticoneButton btnMilktea;
        private SiticoneNetFrameworkUI.SiticoneButton btnFruitTea;
        private SiticoneNetFrameworkUI.SiticoneButton btnRiceMeal;
        private SiticoneNetFrameworkUI.SiticoneButton btnPastry;
        private SiticoneNetFrameworkUI.SiticoneButton btnSnacksPasta;
        private SiticoneNetFrameworkUI.SiticoneButton btnCart;
    }
}